# Generated by Django 5.2.6 on 2025-12-02 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AlterModelOptions(
            name="response",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="attempt",
            name="percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="attempt",
            name="percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="flagged_for_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="response",
            name="teacher_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name="response",
            unique_together={("attempt", "question")},
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["user", "exam"], name="exams_attem_user_id_028ad0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(fields=["status"], name="exams_attem_status_813d45_idx"),
        ),
    ]
