# Generated by Django 5.2.6 on 2025-12-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_attempt_options_alter_response_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="passing_marks",
            field=models.FloatField(default=40),
        ),
        migrations.AlterField(
            model_name="exam",
            name="visibility",
            field=models.CharField(default="PUBLIC", max_length=20),
        ),
    ]
