# Generated by Django 5.2.6 on 2025-10-13 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('HL', 'Higher Level'), ('SL', 'Standard Level')], max_length=10)),
                ('paper_number', models.CharField(blank=True, max_length=50)),
                ('paper_type', models.CharField(choices=[('specimen', 'Specimen'), ('past', 'Past Paper')], max_length=20)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('timezone_label', models.CharField(blank=True, max_length=50)),
                ('session', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='question_papers/%Y/%m/%d/')),
                ('duration_minutes', models.PositiveIntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('allowed_to_upload', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='questionpapers.subject')),
            ],
            options={
                'ordering': ['-year', '-session', 'subject', 'level', 'paper_number'],
            },
        ),
        migrations.CreateModel(
            name='PaperAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='paper_answers/%Y/%m/%d/')),
                ('submitted', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_attempts', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questionpapers.questionpaper')),
            ],
            options={
                'unique_together': {('paper', 'user')},
            },
        ),
    ]
