# Generated by Django 5.2.6 on 2025-10-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpapers', '0003_alter_questionpaper_pdf_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='pdf',
        ),
    ]
