# Generated by Django 5.2.6 on 2025-10-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpapers', '0004_remove_questionpaper_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], help_text='Select Easy/Medium/Hard only if enabled for this paper.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='has_difficulty_levels',
            field=models.BooleanField(default=False, help_text='Enable this if you want to assign Easy/Medium/Hard to each question.'),
        ),
    ]
