# Generated by Django 5.2.6 on 2025-10-19 10:54

import questionpapers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpapers', '0006_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to=questionpapers.models.answer_upload_path),
        ),
        migrations.AlterField(
            model_name='paperattempt',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to=questionpapers.models.answer_upload_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, null=True),
        ),
    ]
