# Generated by Django 5.2.6 on 2025-10-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpapers', '0008_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
