# Generated by Django 5.2.6 on 2025-10-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpapers', '0009_alter_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='level',
            field=models.CharField(choices=[('HL', 'HL'), ('SL', 'SL')], max_length=10),
        ),
    ]
