# Generated by Django 5.2.6 on 2025-10-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpapers', '0010_alter_questionpaper_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='paper_number',
            field=models.CharField(choices=[('1', 'Paper 1'), ('2', 'Paper 2'), ('3', 'Paper 3')], max_length=10),
        ),
    ]
