# Generated by Django 5.2.6 on 2026-01-26 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0007_exam_answer_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("VIDEO", "Video"),
                            ("IMAGE", "Image"),
                            ("NOTES", "Notes"),
                            ("EXTERNAL_LINK", "External link"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="materials/"),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="exams.curriculum",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="exams.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_by_role",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[("MATERIAL", "Material"), ("MOCK_TEST", "Mock test")],
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("sequence_order", models.PositiveIntegerField(default=0)),
                (
                    "priority",
                    models.CharField(
                        choices=[("MANDATORY", "Mandatory"), ("OPTIONAL", "Optional")],
                        default="OPTIONAL",
                        max_length=20,
                    ),
                ),
                ("unlock_override", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.exam",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.material",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["is_active", "type"], name="learning_ma_is_acti_25645b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["curriculum", "topic"], name="learning_ma_curricu_5af31a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningassignment",
            index=models.Index(
                fields=["assigned_to", "sequence_order"],
                name="learning_le_assigne_83a8e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningassignment",
            index=models.Index(
                fields=["assigned_to", "start_at", "end_at"],
                name="learning_le_assigne_472019_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningassignment",
            index=models.Index(
                fields=["assigned_by_role", "priority"],
                name="learning_le_assigne_183b59_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentgroup",
            unique_together={("name", "created_by")},
        ),
    ]
