# Generated by Django 5.2.6 on 2026-01-26 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_attempt_assignment_and_more"),
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="learningassignment",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningassignment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="learningassignment",
            index=models.Index(
                fields=["is_active", "assigned_by"],
                name="learning_le_is_acti_e2c5d7_idx",
            ),
        ),
    ]
